n = input('teste algo: ')
print('O tipo é', type(n))
print('É num?', n.isnumeric())
print('É alfa?', n.isalpha())
print('É num e/ou alfa?', n.isalnum())
print('É espaço?', n.isspace())
print('É maiuscula?', n.isupper())
print('É minuscula?', n.islower())
print('É captalizada?', n.istitle())
print('É imprimivél?', n.isprintable())
print('É decimal?', n.isdecimal())
